### ISSUE TITLE
error while use with vite-plugin-ssr

### ISSUE THREAD

**Issue by caijiehong** [richardtallent/vite-plugin-singlefile#45]
Here is my steps :
1. init project with vite-plugin-ssr, and choose vue-ts template
2. add vite-plugin-singlefile
3. vite.config.ts like this
```
import vue from "@vitejs/plugin-vue";
import ssr from "vite-plugin-ssr/plugin";
import { UserConfig } from "vite";
import { viteSingleFile } from "vite-plugin-singlefile";

const config: UserConfig = {
  plugins: [vue(), ssr(), viteSingleFile()],
};

export default config;

```
4. package.json like this
```
{
  "scripts": {
    "dev": "npm run server",
    "prod": "npm run build && npm run server:prod",
    "build": "vite build",
    "server": "ts-node ./server",
    "server:prod": "cross-env NODE_ENV=production ts-node ./server"
  },
  "dependencies": {
    "@types/compression": "^1.7.2",
    "@types/express": "^4.17.13",
    "@types/node": "^17.0.31",
    "@vitejs/plugin-vue": "^3.0.0",
    "@vue/compiler-sfc": "^3.2.37",
    "@vue/server-renderer": "^3.2.37",
    "compression": "^1.7.4",
    "cross-env": "^7.0.3",
    "express": "^4.18.1",
    "sirv": "^2.0.2",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.4",
    "vite": "^2.9.14",
    "vite-plugin-ssr": "^0.4.9",
    "vite-plugin-singlefile": "^0.10.0",
    "vue": "^3.2.37"
  }
}

```
6. run the command `npm run prod` and got the error like this
```
Invalid value for option "output.inlineDynamicImports" - multiple inputs are not supported when "output.inlineDynamicImports" is true.
error during build:
Error: Invalid value for option "output.inlineDynamicImports" - multiple inputs are not supported when "output.inlineDynamicImports" is true.
    at error (file:///Users/jonescai/git/github/server/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at getInlineDynamicImports (file:///Users/jonescai/git/github/server/node_modules/rollup/dist/es/shared/rollup.js:23442:16)
    at normalizeOutputOptions (file:///Users/jonescai/git/github/server/node_modules/rollup/dist/es/shared/rollup.js:23344:34)
    at getOutputOptions (file:///Users/jonescai/git/github/server/node_modules/rollup/dist/es/shared/rollup.js:23735:12)
    at getOutputOptionsAndPluginDriver (file:///Users/jonescai/git/github/server/node_modules/rollup/dist/es/shared/rollup.js:23730:12)
    at handleGenerateWrite (file:///Users/jonescai/git/github/server/node_modules/rollup/dist/es/shared/rollup.js:23705:74)
    at Object.write (file:///Users/jonescai/git/github/server/node_modules/rollup/dist/es/shared/rollup.js:23673:20)
    at generate (file:///Users/jonescai/git/github/server/node_modules/vite/dist/node/chunks/dep-561c5231.js:43424:64)
    at doBuild (file:///Users/jonescai/git/github/server/node_modules/vite/dist/node/chunks/dep-561c5231.js:43437:26)
    at async build (file:///Users/jonescai/git/github/server/node_modules/vite/dist/node/chunks/dep-561c5231.js:43261:16)
```

**Comment by richardtallent** [comment]
Yeah... this isn't gonna work with SSR. The whole point of this plug-in is to support *serverless* environments.
